<a href="https://colab.research.google.com/github/dmortalla/ztm-tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself


## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
# Create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor using atribute ndim
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the vector dimension
vector.ndim

1

In [9]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7], [5, 3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  3]], dtype=int32)>

In [10]:
# Check the dimension
matrix.ndim

# Note: ndim = number of starting brackets used

2

In [13]:
# Specify the datatype of the elements
matrix_2 = tf.constant([[10., 7.], [3., 2.], [4., 6.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  6.]], dtype=float16)>

In [14]:
# Check ndim
matrix_2.ndim

2

In [17]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3, 0],
                       [4, -1, 5, 6]],
                     [[7, 8, -8, 9],
                      [-2, 10, 11, 12]],
                     [[13, 0, 14, 15],
                      [16, 17, -3, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  0],
        [ 4, -1,  5,  6]],

       [[ 7,  8, -8,  9],
        [-2, 10, 11, 12]],

       [[13,  0, 14, 15],
        [16, 17, -3, 18]]], dtype=int32)>

In [18]:
# Get ndim
tensor.ndim

3

Tensors we've created so far:
* Scalar: a single number of ndim = 0
* Vector: a number with direction of ndim = 1
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers
